# Generated by Django 6.0.2 on 2026-02-15 00:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_work_minutes', models.PositiveIntegerField(default=480)),
                ('daily_break_minutes', models.PositiveIntegerField(default=60)),
                ('break_mode', models.CharField(choices=[('FLEXIBLE', 'Flexible'), ('FIXED', 'Fixed')], default='FLEXIBLE', max_length=20)),
                ('fixed_break_start', models.TimeField(blank=True, null=True)),
                ('fixed_break_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='work.worksession')),
            ],
        ),
        migrations.AddIndex(
            model_name='worksession',
            index=models.Index(fields=['user', 'status'], name='work_workse_user_id_693c40_idx'),
        ),
        migrations.AddIndex(
            model_name='break',
            index=models.Index(fields=['session'], name='work_break_session_21e4c3_idx'),
        ),
    ]
