# Generated by Django 6.0.2 on 2026-02-17 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_organization_user_organization'),
        ('work', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='workpolicy',
            name='organization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='worksession',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_sessions', to='accounts.organization'),
        ),
    ]
