# Generated by Django 6.0.2 on 2026-02-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_backfill_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='worksession',
            name='on_break',
            field=models.BooleanField(default=False),
        ),
    ]
