# Generated by Django 6.0.2 on 2026-02-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0005_add_work_session_on_break'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='worksession',
            name='total_break_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
