from django.urls import path
from .views import (
    start_work, stop_work, break_start, break_end,
    session_break_start, session_break_end,
    policy_view, update_policy, admin_dashboard, weekly_stats,
    create_task, my_tasks, all_tasks, update_task_status,
    my_work_status, my_daily_stats, my_live_session, my_today_timeline,
    my_analytics, my_weekly, admin_summary, admin_user_detail, admin_productivity_ranking,
)

urlpatterns = [
    path("start/", start_work),
    path("stop/", stop_work),
    path("break/start/", break_start),
    path("break/end/", break_end),
    path("break/session/start/", session_break_start),
    path("break/session/end/", session_break_end),
    path("policy/", policy_view),
    path("policy/update/", update_policy),
    path("admin/dashboard/", admin_dashboard),
    path("admin/weekly-stats/", weekly_stats),
    path("tasks/create/", create_task),
    path("tasks/my/", my_tasks),
    path("tasks/all/", all_tasks),
    path("tasks/<int:task_id>/status/", update_task_status),
    path("my-status/", my_work_status),
    path("my-daily-stats/", my_daily_stats),
    path("live-session/", my_live_session),
    path("my-today-timeline/", my_today_timeline),
    path("analytics/me/", my_analytics),
    path("analytics/me/weekly/", my_weekly),
    path("analytics/admin/summary/", admin_summary),
    path("analytics/admin/user/<int:user_id>/", admin_user_detail),
    path("analytics/admin/ranking/", admin_productivity_ranking),
]
